// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guestbook.proto

package guestbook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddPostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostRequest) Reset()         { *m = AddPostRequest{} }
func (m *AddPostRequest) String() string { return proto.CompactTextString(m) }
func (*AddPostRequest) ProtoMessage()    {}
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{0}
}

func (m *AddPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostRequest.Unmarshal(m, b)
}
func (m *AddPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostRequest.Marshal(b, m, deterministic)
}
func (m *AddPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostRequest.Merge(m, src)
}
func (m *AddPostRequest) XXX_Size() int {
	return xxx_messageInfo_AddPostRequest.Size(m)
}
func (m *AddPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostRequest proto.InternalMessageInfo

func (m *AddPostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddPostRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type AddPostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostResponse) Reset()         { *m = AddPostResponse{} }
func (m *AddPostResponse) String() string { return proto.CompactTextString(m) }
func (*AddPostResponse) ProtoMessage()    {}
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{1}
}

func (m *AddPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostResponse.Unmarshal(m, b)
}
func (m *AddPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostResponse.Marshal(b, m, deterministic)
}
func (m *AddPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostResponse.Merge(m, src)
}
func (m *AddPostResponse) XXX_Size() int {
	return xxx_messageInfo_AddPostResponse.Size(m)
}
func (m *AddPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostResponse proto.InternalMessageInfo

func (m *AddPostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{2}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdatePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{3}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

type ListPostsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{4}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

func (m *ListPostsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPostsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{5}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbda7dd58e0f267b, []int{6}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*AddPostRequest)(nil), "AddPostRequest")
	proto.RegisterType((*AddPostResponse)(nil), "AddPostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "UpdatePostResponse")
	proto.RegisterType((*ListPostsRequest)(nil), "ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "ListPostsResponse")
	proto.RegisterType((*Post)(nil), "Post")
}

func init() { proto.RegisterFile("guestbook.proto", fileDescriptor_fbda7dd58e0f267b) }

var fileDescriptor_fbda7dd58e0f267b = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x93, 0x34, 0x7e, 0x5f, 0x72, 0x48, 0x4d, 0x73, 0x74, 0x88, 0xd2, 0xa5, 0x78, 0xea,
	0x64, 0xa1, 0x82, 0x84, 0xc4, 0xc4, 0x9f, 0x81, 0x05, 0x24, 0x14, 0xc4, 0x8c, 0x1a, 0xd9, 0xaa,
	0xac, 0x22, 0x6c, 0xb0, 0x19, 0xe8, 0x47, 0xe2, 0x53, 0x22, 0xdb, 0xa1, 0x0d, 0x69, 0x27, 0xa6,
	0xdc, 0x3d, 0xc9, 0xdd, 0x2f, 0xcf, 0x63, 0x43, 0xbe, 0xfc, 0x10, 0xc6, 0x36, 0x4a, 0xad, 0x98,
	0x7e, 0x57, 0x56, 0xd1, 0x0b, 0x18, 0x5e, 0x71, 0xfe, 0xa0, 0x8c, 0xad, 0xc5, 0x9b, 0x7b, 0x87,
	0x63, 0x20, 0x56, 0xda, 0x17, 0x51, 0xc6, 0xd3, 0x78, 0x96, 0xd5, 0xa1, 0x41, 0x84, 0xb4, 0x51,
	0xfc, 0xb3, 0x4c, 0xbc, 0xe8, 0x6b, 0x7a, 0x0c, 0xf9, 0x66, 0xd6, 0x68, 0xf5, 0x6a, 0x04, 0x0e,
	0x21, 0x91, 0xbc, 0x9d, 0x4c, 0x24, 0xa7, 0xf7, 0x50, 0x3c, 0x69, 0xbe, 0xb0, 0xa2, 0x4b, 0xe8,
	0x7d, 0xb4, 0x25, 0x26, 0xfb, 0x88, 0x83, 0x0e, 0x71, 0x0c, 0xd8, 0x5d, 0x17, 0xa0, 0xf4, 0x06,
	0x46, 0x77, 0xd2, 0x58, 0xa7, 0x99, 0x1f, 0x06, 0x42, 0xaa, 0x17, 0xcb, 0x60, 0x82, 0xd4, 0xbe,
	0xc6, 0x09, 0x64, 0xee, 0xf9, 0x6c, 0xe4, 0x3a, 0xb0, 0x48, 0x7d, 0xe0, 0x84, 0x47, 0xb9, 0x16,
	0xf4, 0x04, 0x8a, 0xce, 0x92, 0xd6, 0xce, 0x04, 0x88, 0x76, 0x42, 0x19, 0x4f, 0x07, 0xb3, 0xc3,
	0x39, 0x61, 0x9e, 0x1b, 0x34, 0x7a, 0x09, 0xa9, 0x6b, 0xff, 0x6e, 0x67, 0xfe, 0x15, 0x43, 0x76,
	0xeb, 0x7e, 0xf7, 0x5a, 0xa9, 0x15, 0x32, 0xf8, 0xdf, 0xc6, 0x89, 0x39, 0xfb, 0x7d, 0x28, 0xd5,
	0x88, 0xf5, 0x92, 0xa6, 0x11, 0x9e, 0x03, 0x6c, 0xc3, 0x40, 0x64, 0x3b, 0x41, 0x57, 0x47, 0x6c,
	0x4f, 0x5a, 0x11, 0x9e, 0x41, 0xb6, 0xb1, 0x8a, 0x05, 0xeb, 0x67, 0x57, 0x21, 0xdb, 0x49, 0x82,
	0x46, 0xcd, 0x3f, 0x7f, 0x61, 0x4e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc7, 0xd4, 0x9b,
	0x43, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuestBookClient is the client API for GuestBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuestBookClient interface {
	AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
}

type guestBookClient struct {
	cc *grpc.ClientConn
}

func NewGuestBookClient(cc *grpc.ClientConn) GuestBookClient {
	return &guestBookClient{cc}
}

func (c *guestBookClient) AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error) {
	out := new(AddPostResponse)
	err := c.cc.Invoke(ctx, "/GuestBook/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestBookClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/GuestBook/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestBookClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/GuestBook/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestBookServer is the server API for GuestBook service.
type GuestBookServer interface {
	AddPost(context.Context, *AddPostRequest) (*AddPostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
}

func RegisterGuestBookServer(s *grpc.Server, srv GuestBookServer) {
	s.RegisterService(&_GuestBook_serviceDesc, srv)
}

func _GuestBook_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestBookServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuestBook/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestBookServer).AddPost(ctx, req.(*AddPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestBook_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestBookServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuestBook/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestBookServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestBook_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestBookServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuestBook/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestBookServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuestBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GuestBook",
	HandlerType: (*GuestBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPost",
			Handler:    _GuestBook_AddPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _GuestBook_UpdatePost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _GuestBook_ListPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guestbook.proto",
}
