workspace(name = "algorithms")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Kythe
http_archive(
    name = "io_kythe",
    strip_prefix = "kythe-0.0.30",
    urls = ["https://github.com/kythe/kythe/archive/v0.0.30.zip"],
)

load("@io_kythe//:setup.bzl", "kythe_rule_repositories")

kythe_rule_repositories()

load("@io_kythe//:external.bzl", "kythe_dependencies")

kythe_dependencies()

# abseil
http_archive(
    name = "absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)

# Google Test
http_archive(
    name = "gtest",
    strip_prefix = "googletest-master",
    urls = ["https://github.com/google/googletest/archive/master.zip"],
)
